### PR TITLE
Added the LinSearch Thing

### PR DESCRIPTION
**Pull request by amalunnikrishnan**

### CODE REVIEW

**Review by RajatJacob — CHANGES_REQUESTED** [review]
Hey @amalunnikrishnan, in #1 we added `target` as a property of the Search ABC. 

We can either undo that, or remove target from this method and use `self._target`.

What are your thoughts?

**Comment by amalunnikrishnan** [comment]
Yeah, both make sense. Which one should we go with? You say.

**Comment by RajatJacob** [comment]
I was thinking either both `items` and `target` should be properties or both should be parameters. ✨Consistency✨

@saral7293 @Sayankarmakar do y'all have any opinions?

**Comment by saral7293** [comment]
keep items as parameter and target as properties.

**Comment by RajatJacob** [comment]
@saral7293 isn't that confusing? Each instance of `LinSearch` will have it's own `target` property, but every time you call the search method, you have to provide a list of items. I think both should be properties or both should be parameters.

**Comment by saral7293** [comment]
Yes rajat you are right.
Let's keep both as parameters. As items was given already a parameter.

**Comment by RajatJacob** [comment]
Oh, but wait. The ABC has a `get_items` method. So `_items` will have to be a property. So maybe we should just make `target` a properly as well.

**Comment by saral7293** [comment]
get_items() is for getting the sorted list items back. and
 _items parameter is for passing the list items.
So _item should be a parameter I guess.

**Comment by RajatJacob** [comment]
As discussed offline, we'll keep both `items` and `target` as properties of the class. I have done it in my branch. I will create a PR soon.

**Review by RajatJacob — APPROVED** [review]

**Pull request merged**
